### ISSUE TITLE
Include HTTP Headers for security

### ISSUE THREAD

**Issue by daro1337** [lorenzophys/secure-share#5]
Include HTTP Headers for securit.
For exmaple:

- X-XSS-Protection
- X-Content-Type-Options
- Strict-Transport-Security
-  X-Frame-Options

Reference: https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html

**Comment by lorenzophys** [comment]
- [x] `X-Frame-Options`
- [x] `X-XSS-Protection`
- [ ] `X-Content-Type-Options`
